server:
  port: 8090
spring:
  redis:
    host: 47.101.37.181
    port: 6379
    password: sch1324!/
    database: 0
dubbo:
  application:
    name: back-web
  registry:
    address: zookeeper://127.0.0.1:2181