server:
  port: 8090
  servlet:
    session:
      cookie:
        path: /
spring:
  session:
    store-type: redis
  redis:
    host: 47.101.37.181
    port: 6379
    password: sch1324!/
    database: 0
    timeout: 3000
    jedis:
      pool:
        max-active: 1024
        max-wait: 3000
        max-idle: 200
        min-idle: 0
dubbo:
  application:
    name: back-web
  registry:
    address: zookeeper://127.0.0.1:2181